sudo: true
language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov

install: 
  - sudo apt-get install -qq g++-5

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
 - ./download_other_githubs.sh
 - ./build_other_githubs.sh
 - ./build_desktop_test.sh
 - ./get_code_cov.sh
 - codecov
 - ./build_desktop.sh
 - ./build_console.sh
